site_name: Vcash docs
theme: readthedocs

pages:
 - Home : index.md
 - Block:
    - Generation:
        - 'Proof-of-Stake': block/generation/proof-of-stake.md
        - 'Proof-of-Work': block/generation/proof-of-work.md
    - block/pruning.md
 - Configuration:
   - Files:
     - 'config.dat': configuration/files/config.dat.md
 - Protocol:
   - Messages:
       - 'ztanswer': protocol/messages/ztanswer.md
       - 'ztlock': protocol/messages/ztlock.md
       - 'ztquestion': protocol/messages/ztquestion.md
       - 'ztvote': protocol/messages/ztvote.md
   - TCP:
       - protocol/TCP/encryption.md
       - protocol/TCP/routing.md
   - UDP:
       - protocol/UDP/encryption.md
       - protocol/UDP/routing.md
 - RPC:
   - Commands:
     - 'backupwallet': RPC/commands/backupwallet.md
     - 'checkwallet': RPC/commands/checkwallet.md
     - 'databasefind': RPC/commands/databasefind.md
     - 'databasestore': RPC/commands/databasestore.md
     - 'dumpprivkey': RPC/commands/dumpprivkey.md
     - 'dumpwallet': RPC/commands/dumpwallet.md
     - 'encryptwallet': RPC/commands/encryptwallet.md
     - 'getaccount': RPC/commands/getaccount.md
     - 'getaccountaddress': RPC/commands/getaccountaddress.md
     - 'getbalance': RPC/commands/getbalance.md
     - 'getblock': RPC/commands/getblock.md
     - 'getblockcount': RPC/commands/getblockcount.md
     - 'getblockhash': RPC/commands/getblockhash.md
     - 'getblocktemplate': RPC/commands/getblocktemplate.md
     - 'getdifficulty': RPC/commands/getdifficulty.md
     - 'getincentiveinfo': RPC/commands/getincentiveinfo.md
     - 'getinfo': RPC/commands/getinfo.md
     - 'getmininginfo': RPC/commands/getmininginfo.md
     - 'getnetworkhashps': RPC/commands/getnetworkhashps.md
     - 'getnewaddress': RPC/commands/getnewaddress.md
     - 'getpeerinfo': RPC/commands/getpeerinfo.md
     - 'getrawtransaction': RPC/commands/getrawtransaction.md
     - 'gettransaction': RPC/commands/gettransaction.md
     - 'importprivkey': RPC/commands/importprivkey.md
     - 'incentive': RPC/commands/incentive.md
     - 'listreceivedbyaccount': RPC/commands/listreceivedbyaccount.md
     - 'listreceivedbyaddress': RPC/commands/listreceivedbyaddress.md
     - 'listsinceblock': RPC/commands/listsinceblock.md
     - 'listtransactions': RPC/commands/listtransactions.md
     - 'repairwallet': RPC/commands/repairwallet.md
     - 'sendmany': RPC/commands/sendmany.md
     - 'sendtoaddress': RPC/commands/sendtoaddress.md
     - 'settxfee': RPC/commands/settxfee.md
     - 'submitblock': RPC/commands/submitblock.md
     - 'validateaddress': RPC/commands/validateaddress.md
     - 'walletdenominate': RPC/commands/walletdenominate.md
     - 'walletlock': RPC/commands/walletlock.md
     - 'walletpassphrase': RPC/commands/walletpassphrase.md
     - 'walletpassphrasechange': RPC/commands/walletpassphrasechange.md
 - Technologies:
    - 'Node Incentives': technologies/node-incentives.md
    - 'ZeroTime': technologies/zerotime.md
